### ISSUE TITLE
lambda trigger installation fails

### ISSUE THREAD

**Issue by shivchelwa** [TIBCOSoftware/flogo-contrib#148]
Tried below options, trigger installation fails!

**$ flogo install trigger github.com/TIBCOSoftware/flogo-contrib/trigger/lambda**
Error: Too many arguments given

Usage:

    flogo  install [-v version][-p] contribution

**$ flogo install github.com/TIBCOSoftware/flogo-contrib/trigger/lambda**
Error opening flogo app project: Invalid project, source directory doesn't exists

**Comment by torresashjian** [comment]
Hi @shivchelwa,

The option 1 flogo install trigger is invalid, so the error is expected.

The option 2 flogo install github.com.... is correct, but it seems like you are executing it from the wrong directory. You need to do it from the root directory of your flogo app. You will know you are in the root directory because there is an src folder in it.

Closing the issue, please reopen it if that doesn't help.
