### ISSUE TITLE
Change log implementation

### ISSUE THREAD

**Issue by torresashjian** [TIBCOSoftware/flogo-contrib#19]
Change log from github.com/op/go-logging to github.com/Sirupsen/logrus

**Comment by joeblew99** [comment]
i prefer logrus also. 

It has many adapters so that logging can easily be mapped to different logging infrastructures out there.
https://github.com/Sirupsen/logrus

Prometheus uses it if your curious about examples.
https://github.com/prometheus/prometheus/blob/master/vendor/github.com/Sirupsen/logrus/logrus.go

**Comment by torresashjian** [comment]
Finished implementation
